language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - printf "\n" | pecl install imagick
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit --coverage-text

after_success: bash <(curl -s https://codecov.io/bash)
