language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - printf "\n" | pecl install imagick
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --coverage-text
